"""Data loaders for Project 05. Infrastructure only: no inference happens here.

All loaded data describes a fictional, synthetic educational simulation.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Dict, List

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

SYNTHETIC_DATA_NOTICE = (
    "All student records, evidence values, and outcomes in this project are synthetic "
    "educational data generated by a Bayesian Network simulator. This is NOT a real "
    "student-evaluation system and must never be used to assess an actual student."
)


def load_bn_schema(path: Path = DATA_DIR / "bn_schema.json") -> dict:
    """Load the Bayesian Network structure (nodes, states, parents, edges)."""
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def load_base_cpt(path: Path = DATA_DIR / "base_cpt.json") -> Dict[str, dict]:
    """Load the conditional probability tables, dropping documentation-only keys."""
    with path.open("r", encoding="utf-8") as handle:
        raw = json.load(handle)
    return {
        name: spec
        for name, spec in raw.items()
        if name not in ("synthetic_data_notice", "format_notes")
    }


def load_scenarios(path: Path = DATA_DIR / "scenarios.json") -> List[dict]:
    """Load the named demo scenarios (little evidence, strong positive, conflicting, CPT sensitivity)."""
    with path.open("r", encoding="utf-8") as handle:
        raw = json.load(handle)
    return raw["scenarios"]


def load_students(path: Path = DATA_DIR / "students_seed42.csv") -> List[Dict[str, str]]:
    """Load the committed synthetic student sample as a list of row dicts."""
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))
